export const REGISTER_USER = 'REGISTER_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const GET_PROJECT = 'GET_PROJECT';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const PROJECT_LOADING = 'PROJECT_LOADING';
export const GET_CLIENT_PROJECT = 'GET_CLIENT_PROJECT';
export const GET_APPLIED_PROJECT = 'GET_APPLIED_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const APPLY_PROJECT = 'APPLY_PROJECT';
export const GET_INDIVIDUAL_PROFILE = 'GET_INDIVIDUAL_PROFILE';
export const GET_APPLICANT_LIST = 'GET_APPLICANT_LIST';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CLEAR_MESSAGE_ROOMS = 'CLEAR_MESSAGE_ROOMS';
export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const GET_MESSAGE_ROOMS = 'GET_MESSAGE_ROOMS';
export const GET_MESSAGE = 'GET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const GET_ROOM_NAME = 'GET_ROOM_NAME';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_INDIVIDUAL_PROFILE = 'CLEAR_INDIVIDUAL_PROFILE';












